chore(logging): update demo logger (#1289)
Update the demo logger to include `extraContext` and `node` content.

Before:
```
BehaviorCopyToClipboardError: [behaviors/copy-to-clipboard]: missing "copy-to-clipboard-value" attribute
```

After:
```
BehaviorCopyToClipboardError: [behaviors/copy-to-clipboard]: missing "copy-to-clipboard-value" attribute,  attributeName: copy-to-clipboard-value, node: <behavior action="copy-to-clipboard" trigger="press" ran-once="true">
```